version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "Matt Bauman and contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "assets/JuliaMono-*.woff2"
precedence = "override"
SPDX-FileCopyrightText = "2020 - 2023, cormullion with Reserved Font Name JuliaMono"
SPDX-License-Identifier = "OFL-1.1-RFN"

